const ActionTypes = {
    PAGEUP: 'PAGEUP',
    SEARCH: 'SEARCH',
    GETLISTSUCCESS: 'GETLISTSUCCESS',
    GETLISTFAIL: 'GETLISTFAIL',
    REQUESTLIST: 'REQUESTLIST',
    SETCURRENTPAGE: 'SETCURRENTPAGE',
    SETFILTER: 'SETFILTER',
    SETSEARCHSTRING: 'SETSEARCHSTRING'
}

export default ActionTypes;