const ActionTypes = {
    PAGEUP: 'PAGEUP',
    SEARCH: 'SEARCH',
    GETLISTSUCCESS: 'GETLISTSUCCESS',
    GETLISTFAIL: 'GETLISTFAIL',
    REQUESTLIST: 'REQUESTLIST',
    SETCURRENTPAGE: 'SETCURRENTPAGE'
}

export default ActionTypes;