const ActionTypes = {
    PAGEUP: 'PAGEUP',
    SEARCH: 'SEARCH',
    GETLISTSUCCESS: 'GETLISTSUCCESS',
    GETLISTFAIL: 'GETLISTFAIL',
    GETJOBSUCCESS: 'GETJOBSUCCESS',
    REQUESTLIST: 'REQUESTLIST',
    SETCURRENTPAGE: 'SETCURRENTPAGE',
    SETFILTER: 'SETFILTER',
    SETSEARCHSTRING: 'SETSEARCHSTRING',
    SWITCHSEARCHMODE: 'SWITCHSEARCHMODE',
}

export default ActionTypes;